[build-system]
requires = ["setuptools >= 77.0.3", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pymmr"
version = "1.0.0"
authors = [
  { name="Bernard Giroux", email="bernard.giroux@inrs.ca" },
]
description = "Code for magnetometric resistivity data modeling and inversion"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "01_LICENSE.txt"}

[project.urls]
Homepage = "https://github.com/bernard-giroux/pymmr"
Issues = "https://github.com/bernard-giroux/pymmr/issues"
